/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.2.1
 *
 * Project: 'Blinky+NUCLEOF756ZG' 
 * Target:  'NUCLEOF756ZG' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f7xx.h"

/* ARM::CMSIS-View:Event Recorder&DAP@1.5.3 */
#define RTE_CMSIS_View_EventRecorder
        #define RTE_CMSIS_View_EventRecorder_DAP
/* ARM::CMSIS:RTOS2:Keil RTX5&Source@5.8.0 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
        #define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
        #define RTE_CMSIS_RTOS2_RTX5_SOURCE     /* CMSIS-RTOS2 Keil RTX5 Source */
/* Keil::CMSIS Driver:VIO:Board&NUCLEO-F756ZG@1.0.0 */
#define RTE_VIO_BOARD
        #define RTE_VIO_NUCLEO_F756ZG
/* Keil::Device:STM32Cube Framework:STM32CubeMX@1.1.0 */
#define RTE_DEVICE_FRAMEWORK_CUBE_MX
/* Keil::Device:STM32Cube HAL:Common@1.3.0 */
#define RTE_DEVICE_HAL_COMMON
/* Keil::Device:STM32Cube HAL:Cortex@1.3.0 */
#define RTE_DEVICE_HAL_CORTEX
/* Keil::Device:STM32Cube HAL:DMA@1.3.0 */
#define RTE_DEVICE_HAL_DMA
/* Keil::Device:STM32Cube HAL:EXTI@1.3.0 */
#define RTE_DEVICE_HAL_EXTI
/* Keil::Device:STM32Cube HAL:GPIO@1.3.0 */
#define RTE_DEVICE_HAL_GPIO
/* Keil::Device:STM32Cube HAL:PWR@1.3.0 */
#define RTE_DEVICE_HAL_PWR
/* Keil::Device:STM32Cube HAL:RCC@1.3.0 */
#define RTE_DEVICE_HAL_RCC
/* Keil::Device:STM32Cube HAL:UART@1.3.0 */
#define RTE_DEVICE_HAL_UART
/* Keil::Device:Startup@1.2.5 */
#define RTE_DEVICE_STARTUP_STM32F7XX    /* Device Startup for STM32F7 */


#endif /* RTE_COMPONENTS_H */
